Added a listerner when new terms of service is created
nextcloud/terms_of_service pull request #895
Opened 2024-01-22 10:49 UTC by SagarGi

### Description
This PR adds an event called `createNewTOSCreatedEvent` when a terms of service is created.

### Why this event needed?
We have a nextcloud application [integration_openproject](https://github.com/nextcloud/integration_openproject) which required this event to be created for one of its feature. 
The feature of this application has such a user "OpenProject" who does not login but does some api request through app password token provided by nextcloud. To sign the Terms of Services a user has to login and then sign those. We are partly able to sign the terms of services through code from the application itself. For that we have to cover three steps in order to sign the Terms of services for the user "OpenProject"

>TOS=Terms Of Services

1. Sign TOS for user "OpenProject" at the time when `terms_of_services` app is enabled
2. Sign TOS for user "OpenProject" at the time it is created and app is enabled already
3. Sign TOS for user "OpenProject" when new TOS is created.

We can cover and handle the first 2 above scenarios but we fail to sign the TOS for 3rd scenario when new TOS is created since there is no event that the app can listen into to sign those TOS for user "OpenProject".

This is just a request or proposal if this application could add an event listener when a new Terms of service is created.
Created a new event in this repository would be really appreciated.

2024-01-22 14:02 UTC, nickvergessen requested changes
I guess you would also need an event (`SignaturesResetEvent`) in 
https://github.com/nextcloud/terms_of_service/blob/d03629a059438194310f773762cfbc644a9f7eb8/lib/Controller/SigningController.php#L116
to cover all of your usecases.

2024-01-22 14:02 UTC, nickvergessen commented on lib/Events/NewTOSCreatedEvent.php
> +class NewTOSCreatedEvent extends Event {
Following the existing naming convention this should be:
```suggestion
class TermsCreatedEvent extends Event {
```

2024-01-23 04:29 UTC, SagarGi commented
> I guess you would also need an event (`SignaturesResetEvent`) in
> 
> https://github.com/nextcloud/terms_of_service/blob/d03629a059438194310f773762cfbc644a9f7eb8/lib/Controller/SigningController.php#L116
> 
> 
> to cover all of your usecases.

@nickvergessen oh yes thanks :smiley: . Resetting clears up the data for the signed users. Will be creating it right away.

2024-01-23 08:41 UTC, nickvergessen commented on lib/Events/ResetSignaturesEvent.php
> +class ResetSignaturesEvent extends Event {
```suggestion
class SignaturesResetEvent extends Event {
```

2024-01-23 09:07 UTC, nickvergessen approved these changes

2024-01-23 09:07 UTC, nickvergessen commented on lib/Events/SignaturesResetEvent.php
> + * @author Roeland Jago Douma <roeland@famdouma.nl>
```suggestion
 * @copyright Copyright (c) 2024 Sagar Gurung  <sagargurung1001@gmail.com>
 *
 * @author Sagar Gurung  <sagargurung1001@gmail.com>
```

2024-01-23 09:07 UTC, nickvergessen commented on lib/Events/TermsCreatedEvent.php
> + * @author Roeland Jago Douma <roeland@famdouma.nl>
```suggestion
 * @copyright Copyright (c) 2024 Sagar Gurung  <sagargurung1001@gmail.com>
 *
 * @author Sagar Gurung  <sagargurung1001@gmail.com>
```

2024-01-23 09:14 UTC, SagarGi commented
@nickvergessen Also app [integration_openproject](https://github.com/nextcloud/integration_openproject) supports the latest 3 version of Nextcloud [25 (will drop soon) , 26 , 27, 28]. So this events needs to be in `terms_of_service` app for the supported NC versions if i am not wrong?.

2024-01-23 09:41 UTC, nickvergessen commented
Should be yeah

2024-01-23 09:41 UTC, nickvergessen commented
But I'm not maintaining the app anymore, so pinging @GretaD and @max-nextcloud

2024-01-23 09:57 UTC, max-nextcloud reviewed
All in all looks good to me. Some minor comments about docs.

Usually I am not fond of backporting enhancements to older versions - but okay to make an exception here for the versions still in maintenance (i.e. >= 26).

2024-01-23 09:57 UTC, max-nextcloud commented on lib/Events/SignaturesResetEvent.php
> + */
docs are from a different event.

2024-01-23 09:57 UTC, max-nextcloud commented on lib/Events/TermsCreatedEvent.php
> + */
docs are from a different event.

2024-01-24 03:42 UTC, SagarGi commented
> All in all looks good to me. Some minor comments about docs.
> 
> Usually I am not fond of backporting enhancements to older versions - but okay to make an exception here for the versions still in maintenance (i.e. >= 26).

Thanks. we are dropping the support for NC-25 very soon. Its good to have these from NC version>=26.

2024-01-24 14:11 UTC, max-nextcloud approved these changes

2024-01-24 14:14 UTC, max-nextcloud commented
/backport to stable28

2024-01-24 14:17 UTC, max-nextcloud commented
/backport to stable27

2024-01-24 14:18 UTC, max-nextcloud commented
/backport to stable26

2024-01-24 14:18 UTC, merged

2024-01-24 21:02 UTC, max-nextcloud commented
/backport to stable28

2024-01-24 21:02 UTC, max-nextcloud commented
/backport to stable27

2024-01-24 21:03 UTC, max-nextcloud commented
/backport to stable26